development:
  adapter: postgresql
  database: OmniBot_development
  template: template0

test:
  adapter: postgresql
  database: OmniBot_test
  template: template0

production:
  adapter: postgresql
  database: OmniBot_production
  template: template0
